ORGS: dict[str, list[str]] = {
    "UK":          ["alphagov", "i-dot-ai", "co-cddo", "nhsengland",
                    "DWPDigital", "hmrc", "ministryofjustice",
                    "ScottishGovernment"],
    "Canada":      ["canada-ca", "cds-snc"],
    "Singapore":   ["govtechsg", "opengovsg"],
    "USA":         ["GSA", "18F", "uswds", "CDCgov", "USDS"],
    "Australia":   ["AusDTO", "govau", "ServiceNSW"],
    "New Zealand": ["ServiceInnovationLab", "GOVTNZ"],
    "France":      ["betagouv", "numerique-gouv", "etalab"],
    "Germany":     ["digitalservicebund"],
    "Netherlands": ["minbzk", "nl-design-system"],
    "Sweden":      ["diggsweden"],
    "Denmark":     ["digst"],
    "EU":          ["ec-europa"],
    "Estonia":     ["e-gov"],
    "India":       ["egovernments", "mosip"],
    "Brazil":      ["servicosgovbr"],
    "Taiwan":      ["g0v"],
}